### ISSUE TITLE
次数限制，归属地

### ISSUE THREAD

**Issue by liudianliang** [digglife/cnbankcard#2]
感谢提供，有没有查询次数的限制，有没有开卡行归属地信息？

**Comment by digglife** [comment]
@liudianliang 
1. 使用中未发现有次数限制
2. 支付宝的 API 没有查询归属地的参数，这个信息我也很想要 :smile:

**Comment by zhongzhaoxi** [comment]
支付宝这个接口是开放的吗 接口不会突然变吧

**Comment by digglife** [comment]
@zhongzhaoxi 

这个接口是我无意中发现的，支付宝并没有公开的文档说明，但是也并未设限。
从我发现到如今已经两年有余，一直都是可用的，我估计也不会变了。当然，我觉得如果是工作相关的生产环境要用，还是让老板花钱买那种按次数付费的 API 比较好。
