### ISSUE TITLE
如何获取英文名称呢？

### ISSUE THREAD

**Issue by hllGitHub** [digglife/cnbankcard#4]
支付宝的页面内只能爬到中文的银行名称，但是我想获取那些银行的英文名称呢？请问有什么比较合适的方式？

**Comment by digglife** [comment]
可以搜索一下。比如爬这个Wiki：https://zh.m.wikipedia.org/zh-hans/%E4%B8%AD%E5%9B%BD%E5%A4%A7%E9%99%86%E9%93%B6%E8%A1%8C%E5%88%97%E8%A1%A8

**Comment by hllGitHub** [comment]
爬了这个，数据跟支付宝的不太一致。其余的估计得手动处理了。
